services:
  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka_container
    ports:
      - 9094:9094
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # - KAFKA_CFG_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS=localhost:9093
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  spark-master:
    image: bitnami/spark:3.5.5
    container_name: spark-master
    ports:
      - 7077:7077  # Spark master port
      - 8080:8080  # Spark web UI
      - 4040:4040
    volumes:
      - ./spark:/opt/spark-app     # mount for Spark scripts
      # - ./data:/data                   # mount for input data
    environment:
      - SPARK_MODE=master
    depends_on:
      - kafka

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    ports:
      - 8081:8081  # Spark worker web UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master

  postgres:
    image: postgres:17
    container_name: postgres_container
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - spark-worker

volumes:
  pgdata:
