-- SELECT * FROM unifieddata;

SELECT DATE(START_TIME), AVG("air_temperature")
FROM UNIFIEDDATA
GROUP BY DATE(START_TIME)
ORDER BY DATE(START_TIME);

SELECT DATE(START_TIME), AVG("air_moisture")
FROM UNIFIEDDATA
GROUP BY DATE(START_TIME)
ORDER BY DATE(START_TIME);

SELECT DATE(START_TIME), AVG("air_light")
FROM UNIFIEDDATA
GROUP BY DATE(START_TIME)
ORDER BY DATE(START_TIME);

SELECT DATE(START_TIME), AVG("air_windDirection")
FROM UNIFIEDDATA
GROUP BY DATE(START_TIME)
ORDER BY DATE(START_TIME);

SELECT DATE(START_TIME), AVG("air_pm2dot5")
FROM UNIFIEDDATA
GROUP BY DATE(START_TIME)
ORDER BY DATE(START_TIME);

SELECT DATE(START_TIME), AVG("air_pm10")
FROM UNIFIEDDATA
GROUP BY DATE(START_TIME)
ORDER BY DATE(START_TIME);

SELECT DATE(START_TIME), AVG("air_CO")
FROM UNIFIEDDATA
GROUP BY DATE(START_TIME)
ORDER BY DATE(START_TIME);